#!/bin/sh
set -e

# Map CALCOM_* prefixed Doppler secrets to the env vars Cal.com expects
export DATABASE_URL="${CALCOM_DATABASE_URL}"
export DATABASE_DIRECT_URL="${CALCOM_DATABASE_DIRECT_URL}"
export NEXTAUTH_SECRET="${CALCOM_NEXTAUTH_SECRET}"
export NEXTAUTH_URL="${CALCOM_NEXTAUTH_URL}"
export NEXT_PUBLIC_WEBAPP_URL="${CALCOM_NEXT_PUBLIC_WEBAPP_URL}"
export NEXT_PUBLIC_API_V2_URL="${CALCOM_NEXT_PUBLIC_API_V2_URL}"
export CALENDSO_ENCRYPTION_KEY="${CALCOM_CALENDSO_ENCRYPTION_KEY}"
export CALCOM_LICENSE_KEY="${CALCOM_CALCOM_LICENSE_KEY}"
export NEXT_PUBLIC_LICENSE_CONSENT="${CALCOM_NEXT_PUBLIC_LICENSE_CONSENT:-agree}"

# SMTP Configuration (Google Workspace)
export EMAIL_FROM="${CALCOM_EMAIL_FROM}"
export EMAIL_SERVER_HOST="${CALCOM_EMAIL_SERVER_HOST}"
export EMAIL_SERVER_PORT="${CALCOM_EMAIL_SERVER_PORT}"
export EMAIL_SERVER_USER="${CALCOM_EMAIL_SERVER_USER}"
export EMAIL_SERVER_PASSWORD="${CALCOM_EMAIL_SERVER_PASSWORD}"

export NODE_ENV="production"

# Hand off to Cal.com's original entrypoint
exec docker-entrypoint.sh /calcom/scripts/start.sh
